# Generated by Django 3.0.8 on 2020-09-14 06:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('body', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 9, 13, 23, 7, 46, 694723))),
                ('liked', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('followers', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('likes', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='network.Post')),
            ],
        ),
    ]
