# Generated by Django 3.0.8 on 2020-09-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200916_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='img/avatar.png'),
        ),
    ]
