# Generated by Django 3.0.8 on 2020-09-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='img/avatar.png'),
        ),
    ]
