# Generated by Django 3.0.8 on 2020-09-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
