# Generated by Django 3.0.8 on 2020-09-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_auto_20200917_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(default="{% static 'network/img/avatars/avatar_bucket.png' %}"),
        ),
    ]
