# Generated by Django 3.0.8 on 2020-09-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_auto_20200917_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
