# Generated by Django 3.0.8 on 2020-09-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(default="{% static 'network/img/avatars/avatar_bucket.png' %}"),
        ),
    ]
