# Generated by Django 3.0.8 on 2020-09-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0029_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='avatar_bucket.png'),
        ),
    ]
