# Generated by Django 3.0.8 on 2020-09-19 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0031_auto_20200917_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_count',
        ),
        migrations.AddField(
            model_name='user',
            name='like_count',
            field=models.ManyToManyField(related_name='liked_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
