# Generated by Django 3.0.8 on 2020-09-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0032_auto_20200918_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
