# Generated by Django 3.0.8 on 2020-09-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0033_remove_post_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='like_count',
        ),
        migrations.AddField(
            model_name='post',
            name='liked_user_count',
            field=models.ManyToManyField(related_name='liked_id', to='network.Post'),
        ),
    ]
