# Generated by Django 3.0.8 on 2020-09-19 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0034_auto_20200918_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likers',
            field=models.ManyToManyField(related_name='liked_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_count',
        ),
        migrations.AddField(
            model_name='user',
            name='like_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
