# Generated by Django 3.0.8 on 2020-09-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0035_auto_20200919_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_count',
        ),
    ]
