# Generated by Django 3.0.8 on 2020-09-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0036_remove_user_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likers',
        ),
        migrations.AddField(
            model_name='user',
            name='likers',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
