# Generated by Django 3.0.8 on 2020-09-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0037_auto_20200921_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='likers',
            new_name='like_count',
        ),
    ]
