# Generated by Django 3.0.8 on 2020-09-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0038_auto_20200921_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_count',
        ),
    ]
